drivers/crypto/hisilicon: Don't build for RISC-V
These drivers are enabled to build on RISC-V when ACPI option
is enabled with allmodconfig configuration. However, there
are build errors like below.

drivers/crypto/hisilicon/qm.c:627:10: error: invalid output constraint '+Q' in asm
                       "+Q" (*((char __iomem *)fun_base))
                       ^
drivers/crypto/hisilicon/qm.c:5207:39: error: shift count >= width of type [-Werror,-Wshift-count-overflow]
        ret = dma_set_mask_and_coherent(dev, DMA_BIT_MASK(64));
                                             ^~~~~~~~~~~~~~~~
./include/linux/dma-mapping.h:76:54: note: expanded from macro 'DMA_BIT_MASK'
                                                     ^ ~~~

Since it looks like it is intended for ARM64 with inline assembly,
disable it for RISC-V even when ACPI is enabled.

Signed-off-by: Sunil V L <sunilvl@ventanamicro.com>